default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DATABASE_ROLE_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: goated_orari_unipd_development

test:
  <<: *default
  database: goated_orari_unipd_test

production:
  <<: *default
  database: goated_orari_unipd_production
  username: <%= ENV['DB_PROD_USERNAME'] %>  # Use production env variable
  password: <%= ENV['DB_PROD_PASSWORD'] %>  # Use production env variable
  host: <%= ENV['DB_HOST'] %>  # Set host for production (e.g., cloud host)
